########################################################################################### docker.io/consul
# docker.io/consul
# Tag list: https://explore.ggcr.dev/?repo=consul
#"docker.io/library/consul:/^(1.11)(.[0-9]+)*(-rc[0-9]*)?$/":
#"docker.io/library/consul:/^(1.15)(.[0-9]+)*(-rc[0-9]*)?$/":

########################################################################################### docker.io/adoptopenjdk
# docker.io/adoptopenjdk/openjdk11
#"docker.io/adoptopenjdk/openjdk11:latest":
#"docker.io/adoptopenjdk/openjdk11:debian":

########################################################################################### docker.io/eclipse-temurin
# docker.io/eclipse-temurin 11
# Tag list: https://explore.ggcr.dev/?repo=eclipse-temurin
#"docker.io/library/eclipse-temurin:11,11-alpine,11-centos7,11-focal,11-jammy":
#"docker.io/library/eclipse-temurin:11-jdk,11-jdk-alpine,11-jdk-centos7,11-jdk-focal,11-jdk-jammy":
#"docker.io/library/eclipse-temurin:11-jre,11-jre-alpine,11-jre-centos7,11-jre-focal,11-jre-jammy":

# docker.io/eclipse-temurin 17
# Tag list: https://explore.ggcr.dev/?repo=eclipse-temurin
#"docker.io/library/eclipse-temurin:17,17-alpine,17-centos7,17-focal,17-jammy":
#"docker.io/library/eclipse-temurin:17-jdk,17-jdk-alpine,17-jdk-centos7,17-jdk-focal,17-jdk-jammy":
#"docker.io/library/eclipse-temurin:17-jre,17-jre-alpine,17-jre-centos7,17-jre-focal,17-jre-jammy":

# docker.io/eclipse-temurin 21
# Tag list: https://explore.ggcr.dev/?repo=eclipse-temurin
#"docker.io/library/eclipse-temurin:21,21-alpine,21-jammy":
#"docker.io/library/eclipse-temurin:21-jdk,21-jdk-alpine,21-jdk-jammy":
#"docker.io/library/eclipse-temurin:21-jre,21-jre-alpine,21-jre-jammy":

########################################################################################### docker.io/jetbrains
# docker.io/jetbrains/teamcity-server
# Tag list: https://explore.ggcr.dev/?repo=docker.io/jetbrains/teamcity-server
#"docker.io/jetbrains/teamcity-server:/^(2024|2025|2026)(.[0-9]+)*$/":

# docker.io/jetbrains/teamcity-agent
# Tag list: https://explore.ggcr.dev/?repo=docker.io/jetbrains/teamcity-agent
#"docker.io/jetbrains/teamcity-agent:/^(2024|2025|2026)(.[0-9]+)*$/":

# docker.io/jetbrains/qodana-jvm-community
# Tag list: https://explore.ggcr.dev/?repo=jetbrains/qodana-jvm-community
#"docker.io/jetbrains/teamcity-agent:latest":

########################################################################################### docker.io/nginx
# docker.io/nginx
# Tag list: https://explore.ggcr.dev/?repo=nginx
#"docker.io/library/nginx:/stable.*/":
#"docker.io/library/nginx:latest":

########################################################################################### docker.io/openresty
# docker.io/openresty/openresty
# Tag list: https://explore.ggcr.dev/?repo=docker.io/openresty/openresty
#"docker.io/openresty/openresty:/latest.*/":
#"docker.io/openresty/openresty:alpine,bionic,bookworm,bullseye,buster,centos,fedora,focal,jammy,jessie,rocky,stretch,trusty,wheezy,xenial":

# Tag list: https://explore.ggcr.dev/?repo=docker.io/clamav/clamav
#"docker.io/clamav/clamav:latest,latest_base,stable_base,stable,1.3.1,1.3.1_base,1.3,1.3_base":

########################################################################################### docker.io/elasticsearch
# docker.io/elasticsearch
# Tag list: https://explore.ggcr.dev/?repo=elasticsearch
# Tag list: https://explore.ggcr.dev/?repo=docker.elastic.co/elasticsearch/elasticsearch
#"docker.elastic.co/elasticsearch/elasticsearch:7.6.2":
#"docker.elastic.co/elasticsearch/elasticsearch:7.10.2":
#"docker.elastic.co/elasticsearch/elasticsearch:7.17.22":
#"docker.elastic.co/elasticsearch/elasticsearch:8.14.1":

########################################################################################### docker.io/logstash
# docker.io/logstash
# Tag list: https://explore.ggcr.dev/?repo=logstash
# Tag list: https://explore.ggcr.dev/?repo=docker.elastic.co/logstash/logstash
#"docker.elastic.co/logstash/logstash:7.6.2":
#"docker.elastic.co/logstash/logstash:7.10.2":
#"docker.elastic.co/logstash/logstash:7.17.22":
#"docker.elastic.co/logstash/logstash:8.14.1":

########################################################################################### docker.io/kibana
# docker.io/kibana
# Tag list: https://explore.ggcr.dev/?repo=kibana
# Tag list: https://explore.ggcr.dev/?repo=docker.elastic.co/kibana/kibana
#"docker.elastic.co/kibana/kibana:7.6.2":
#"docker.elastic.co/kibana/kibana:7.10.2":
#"docker.elastic.co/kibana/kibana:7.17.22":
#"docker.elastic.co/kibana/kibana:8.14.1":

########################################################################################### filebeat 官方没有, 风格模仿
# docker.io/kibana
# Tag list: https://explore.ggcr.dev/?repo=docker.elastic.co/beats/filebeat
#"docker.elastic.co/beats/filebeat:7.6.2":
#"docker.elastic.co/beats/filebeat:7.10.2":
#"docker.elastic.co/beats/filebeat:7.17.22":
#"docker.elastic.co/beats/filebeat:8.14.1":

########################################################################################### kubernetes
########################################################################################### registry.k8s.io/kube-apiserver
# registry.k8s.io/kube-apiserver
# Tag list: https://explore.ggcr.dev/?repo=registry.k8s.io/kube-apiserver
#"registry.k8s.io/kube-apiserver:/^(v1.25)(.[0-9]+)*$/":
#"registry.k8s.io/kube-apiserver:/^(v1.26)(.[0-9]+)*$/":
#"registry.k8s.io/kube-apiserver:/^(v1.27)(.[0-9]+)*$/":
#"registry.k8s.io/kube-apiserver:/^(v1.28)(.[0-9]+)*$/":
#"registry.k8s.io/kube-apiserver:/^(v1.29)(.[0-9]+)*$/":
#"registry.k8s.io/kube-apiserver:/^(v1.30)(.[0-9]+)*$/":

########################################################################################### registry.k8s.io/kube-controller-manager
# registry.k8s.io/kube-controller-manager
# Tag list: https://explore.ggcr.dev/?repo=registry.k8s.io/kube-controller-manager
#"registry.k8s.io/kube-controller-manager:/^(v1.25)(.[0-9]+)*$/":
#"registry.k8s.io/kube-controller-manager:/^(v1.26)(.[0-9]+)*$/":
#"registry.k8s.io/kube-controller-manager:/^(v1.27)(.[0-9]+)*$/":
#"registry.k8s.io/kube-controller-manager:/^(v1.28)(.[0-9]+)*$/":
#"registry.k8s.io/kube-controller-manager:/^(v1.29)(.[0-9]+)*$/":
#"registry.k8s.io/kube-controller-manager:/^(v1.30)(.[0-9]+)*$/":

########################################################################################### registry.k8s.io/kube-scheduler
# registry.k8s.io/kube-scheduler
# Tag list: https://explore.ggcr.dev/?repo=registry.k8s.io/kube-scheduler
#"registry.k8s.io/kube-scheduler:/^(v1.25)(.[0-9]+)*$/":
#"registry.k8s.io/kube-scheduler:/^(v1.26)(.[0-9]+)*$/":
#"registry.k8s.io/kube-scheduler:/^(v1.27)(.[0-9]+)*$/":
#"registry.k8s.io/kube-scheduler:/^(v1.28)(.[0-9]+)*$/":
#"registry.k8s.io/kube-scheduler:/^(v1.29)(.[0-9]+)*$/":
#"registry.k8s.io/kube-scheduler:/^(v1.30)(.[0-9]+)*$/":

########################################################################################### registry.k8s.io/kube-proxy
# registry.k8s.io/kube-proxy
# Tag list: https://explore.ggcr.dev/?repo=registry.k8s.io/kube-proxy
#"registry.k8s.io/kube-proxy:/^(v1.25)(.[0-9]+)*$/":
#"registry.k8s.io/kube-proxy:/^(v1.26)(.[0-9]+)*$/":
#"registry.k8s.io/kube-proxy:/^(v1.27)(.[0-9]+)*$/":
#"registry.k8s.io/kube-proxy:/^(v1.28)(.[0-9]+)*$/":
#"registry.k8s.io/kube-proxy:/^(v1.29)(.[0-9]+)*$/":
#"registry.k8s.io/kube-proxy:/^(v1.30)(.[0-9]+)*$/":

########################################################################################### registry.k8s.io/coredns/coredns
# registry.k8s.io/coredns/coredns
# Tag list: https://explore.ggcr.dev/?repo=registry.k8s.io/coredns/coredns
#"registry.k8s.io/coredns/coredns:/^v([0-9]+)(.[0-9]+)*$/":
#"registry.k8s.io/coredns/coredns:/^(v1.10|v1.11|v1.12|v1.13)(.[0-9]+)*$/":

########################################################################################### registry.k8s.io/pause
# registry.k8s.io/pause
# Tag list: https://explore.ggcr.dev/?repo=registry.k8s.io/pause
#"registry.k8s.io/pause:/^([0-9]+)(.[0-9]+)*$/":

########################################################################################### registry.k8s.io/etcd
# registry.k8s.io/etcd
# Tag list: https://explore.ggcr.dev/?repo=registry.k8s.io/etcd
#"registry.k8s.io/etcd:/^(3|4)(.[0-9]+)*(-[0-9]+)?$/":

########################################################################################### docker.io/calico/kube-controllers
# docker.io/calico/kube-controllers
# Tag list: https://explore.ggcr.dev/?repo=calico/kube-controllers
#"docker.io/calico/kube-controllers:/^(v3.25)(.[0-9]+)*$/":
#"docker.io/calico/kube-controllers:/^(v3.26)(.[0-9]+)*$/":
#"docker.io/calico/kube-controllers:/^(v3.27)(.[0-9]+)*$/":
#"docker.io/calico/kube-controllers:/^(v3.28)(.[0-9]+)*$/":

########################################################################################### docker.io/calico/cni
# docker.io/calico/cni
# Tag list: https://explore.ggcr.dev/?repo=calico/cni
#"docker.io/calico/cni:/^(v3.25)(.[0-9]+)*$/":
#"docker.io/calico/cni:/^(v3.26)(.[0-9]+)*$/":
#"docker.io/calico/cni:/^(v3.27)(.[0-9]+)*$/":
#"docker.io/calico/cni:/^(v3.28)(.[0-9]+)*$/":

########################################################################################### docker.io/calico/node
# docker.io/calico/node
# Tag list: https://explore.ggcr.dev/?repo=calico/node
#"docker.io/calico/node:/^(v3.25)(.[0-9]+)*$/":
#"docker.io/calico/node:/^(v3.26)(.[0-9]+)*$/":
#"docker.io/calico/node:/^(v3.27)(.[0-9]+)*$/":
#"docker.io/calico/node:/^(v3.28)(.[0-9]+)*$/":

########################################################################################### ghcr.io/kube-vip/kube-vip
# ghcr.io/kube-vip/kube-vip
# Tag list: https://explore.ggcr.dev/?repo=ghcr.io/kube-vip/kube-vip
#"ghcr.io/kube-vip/kube-vip:latest":
#"ghcr.io/kube-vip/kube-vip:/^v([0-9]+)(.[0-9]+)*$/":
