name: Target Sync Image For Issue
on:
  issues:
    types:
      - opened

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'sync image')
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions: # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
      issues: write
      repository-projects: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Issue
        id: get-image
        env:
          IMAGE: "${{ github.event.issue.title }}"
        run: |
          chmod +x ./hack/correct-image.sh ./hack/verify-allows.sh
          # 生成allows.txt
          python hack/generate_allow.py
          
          cat allows.txt
          
          ORIGIN_IMAGE="${IMAGE}"
          CORRECT_IMAGE="$(./hack/correct-image.sh "${ORIGIN_IMAGE}")"
          if [[ "${CORRECT_IMAGE}" == "" ]]; then
            gh issue comment ${{ github.event.issue.number }} -b "镜像 '${ORIGIN_IMAGE}' 不是一个镜像"
            exit 1
          fi
          
          # 镜像格式检测
          if [[ "${CORRECT_IMAGE}" != "${ORIGIN_IMAGE}" ]]; then
              gh issue comment ${{ github.event.issue.number }} -b "镜像 '${ORIGIN_IMAGE}' 不存在呢, 也许应该是 '${CORRECT_IMAGE}'"
            exit 1
          fi
          
          # 镜像白名单检测
          if ! ./hack/verify-allows.sh ./allows.txt "${ORIGIN_IMAGE}"; then
            gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 不在允许列表中, 不支持同步和访问"
            exit 1
          fi
          
          echo "image=${ORIGIN_IMAGE}" >> $GITHUB_OUTPUT

      - name: Check Image
        run: |
          ORIGIN_IMAGE="${{ steps.get-image.outputs.image }}"
          gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 同步中...<br>[详情请查看](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"

      - name: Generate Image yaml
        run: |
          python hack/generate_issue_images.py ${{ github.event.issue.number }} ${{ steps.get-image.outputs.image }}
          cat issue_images.yaml
          cat target_images_${{ github.event.issue.number }}.yaml

      - name: Image Sync Action
#        with:
#          auth_file: ./config/auth.yaml
#          images_file: ./issue_images.yaml
#          proc: 10
#          # stderr 重定向至 stdout
#          append_script: '2>&1 | grep -v "Auth information not found" | grep -v "Finish synchronizing blob sha256:"'
        env:
          ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_USERNAME: ${{ secrets.ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_USERNAME }}
          ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_PASSWORD: ${{ secrets.ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_PASSWORD }}
        run: |
          ./bin/image-syncer --auth=./config/auth.yaml --images=./issue_images.yaml --proc=10 --retries=2 2>&1 | grep -v "Auth information not found" | grep -v "Finish synchronizing blob sha256:"

      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-beijing.aliyuncs.com"
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - run: ossutil cp -f target_images_${{ github.event.issue.number }}.yaml oss://${{ secrets.OSS_BUCKET }}/
      - run: ossutil ls oss://${{ secrets.OSS_BUCKET }}

      - name: Sync Images
        run: |
          gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 转储完成, 私有化成功请查看私有镜像仓库: http://docker-hosted.nstl-dev.com/"
          gh issue edit ${{ github.event.issue.number }} --add-label "sync image succeeded" -b "IMAGE SYNC"
          gh issue close ${{ github.event.issue.number }} --reason "completed"

      - name: Fail Sync
        if: failure()
        run: |
          ORIGIN_IMAGE="${{ steps.get-image.outputs.image }}"
          gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 同步失败[详情请查看](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})<br>请检查镜像是否存在以及在白名单, [查看成功例子](https://github.com/${{ github.repository }}/issues?q=is%3Aissue+is%3Aclosed+label%3A%22sync+image+succeeded%22)<br>如有疑问请回复 /auto-cc 召唤帮助"
          gh issue edit ${{ github.event.issue.number }} --add-label "sync image failure" -b "IMAGE SYNC"
          gh issue close ${{ github.event.issue.number }} --reason "not planned"